allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.library")) {
            def androidExt = project.android
            if (androidExt.namespace == null) {
                def manifestFile = project.file("${project.projectDir}/src/main/AndroidManifest.xml")
                def packageName = new groovy.xml.XmlSlurper().parse(manifestFile).@package.toString()
                androidExt.namespace = packageName
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
